export enum AppErrorsMessages {
  EMAIL_ALREADY_EXISTS = "Email already registered.",
  EMAIL_REQUIRED = "Email requiied.",
  INVALID_CREDENTIALS = "Invalid credentials.",
  INVALID_REFRESH_TOKEN = "Invalid refresh token.",
  NOT_AUTHORIZED = "Not authorized.",
  NO_TOKEN_PROVIDED = "No token provided.",
  INVALID_TOKEN = "Invalid token.",
  FAIL_AUTH_TOKEN = "Invalid token.",
  FAIL_GET_TOKEN = "Failed to get token.",
  ERROR_SIGNUP = "Error signing up.",
  ERROR_SAVE_USER = "Error saving user.",
  ERROR_UPDATE_USER = "Error updating user.",
  ERROR_DELETE_USER = "Error deleting user.",
  USER_ALREADY_EXISTS = "User already registered.",
  USER_NOT_FOUND = "User not found.",
  USER_REQUIRED = "User required.",
  USER_INVALID = "User invalid.",
  USER_CREATING = "Error creating user.",
  USER_UPDATING = "Error updating user.",
  USER_ID_MISSING = "User ID missing.",
  USER_ASSOCIATED_TO_PAGE_NOT_FOUND = "User associated to page doesn't exist.",
  USERID_OR_EMAIL_REQUIRED = "UserID or user email are required.",
  USER_HAS_NO_PAGES = "User has no pages.",
  PAGE_REQUIRED = "Page required.",
  PAGE_ID_MISSING = "Page ID missing.",
  PAGE_INVALID = "Page invalid.",
  PAGE_CREATING = "Error creating page.",
  PAGE_UPDATING = "Error updating page.",
  PAGE_DELETING = "Error deleting page.",
  PAGE_NOT_FOUND = "Page not found.",
  PAGE_URL_ALREADY_EXIST = "URL already exist.",
  PAGE_VIEW_INCREMENT = "Error to increment page views",
  URL_MISSING_IN_PARAMS = "URL missing in params.",
  NOT_CREATED = "Not created.",
  NOT_UPDATED = "Not updated.",
  NOT_DELETED = "Not deleted.",
  INTERNAL_ERROR = "Internal error.",
  TOKEN_VERIFIER_MIDDLEWARE = "Error in token verifier middleware.",
  TOKEN_FROM_ANOTHER_USER = "Token doesn't belong to the user.",
  INVALID_REQUEST = "Invalid request.",
  PASSWORDS_NOT_MATCH = "Passwords don't match.",
  PASSWORDS_REQUIRED = "Passwords required.",
  SIGNOUT = "Failed to sign out.",
}

export enum AppSuccessMessages {
  SIGNOUT = "User successfully signed out.",
  PAGE_DELETED = "Page successfully deleted.",
}
